input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [level] {
    mutate {
      add_field => { "[@metadata][level]" => "%{level}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "observatory-logs"
  }
  stdout { codec => rubydebug }
}
