# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - obs-api-amen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: am3nn/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F5075E3437BF46BEAA09D39EC76E37DD }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_F4A5DAA77F254FBD956741EC5F6F2A23 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: am3nn/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F5075E3437BF46BEAA09D39EC76E37DD }}/devops-observatory:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F48DCAF474B74C9A89E750CB5A1FC497 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6ED6FB84A12B4FB199B24F7940542538 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F48573F19863409BB322A19B71996695 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'obs-api-amen'
          slot-name: 'Production'
          images: 'am3nn/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F5075E3437BF46BEAA09D39EC76E37DD }}/devops-observatory:${{ github.sha }}'
          